# docker compose up --build

services:
  app:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "300"
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    depends_on:
      - postgres
      - sqs

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: leilao
      POSTGRES_PASSWORD: leilao
      POSTGRES_DB: leilao
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sqs:
    image: localstack/localstack:3
    environment:
      SERVICES: sqs
      DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  postgres_data:
  localstack_data:
